# Science Research Data Analysis Template

## Goal
Use this notebook to analyze a dataset, visualize patterns, and draw conclusions.

## Research Questions
(Write your questions here)

## Import Libraries

In this step, you will import the libraries needed for data analysis, mathematical operations and data visualization. 

Before running the import cell, make sure to install any required libraries using the pip cell below. Then run the import cell to load them into your notebook. 

Add additional imports as needed for your specific project, you may need to install via pip before importing.

In [6]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.4)
Requirement already satisfied: matplotlib in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: seaborn in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Set Seaborn Style

This just sets the default style of graphs and plots, you can find seaborn docs on this to change the appearance.

In [6]:
sns.set()

## Load Data `.read_csv("data_name_here")`

You must drag your dataset into the left hand toolbar and name it approprietely. You can then call the name and access.

In [7]:
# Replace with your file
df = pd.read_csv("pokemon.csv")

df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

## Displaying Dataset Size `.head("number here")`

This displays the first N rows of the dataset (counting from the beginning).

Example: df.head(5) → shows the first 5 rows

In [8]:
df.head(5)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

## Displaying Dataset Size `.tail(number here)`

This displays the last *N* rows of the dataset (counting from the end).

Example:
df.tail(5)  → shows the last 5 rows

In [9]:
df.tail(5)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

## Displaying Dataset `Size .shape()`

This can display how many rows and columns are in the data set. (Rows x Columns)

In [31]:
print(f"Dataset Size → Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Dataset Size → Rows: 801, Columns: 41

## Display all Columns `.columns`

This will show you all the column headings in your data set.

In [11]:
print(df.columns)

Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='str')

## Dataset Information `.info()`

This section provides an overview of your dataset, including:

- The number of columns
- The names of each column
- The number of non-null (filled) values in each column
- The data type of each column (e.g., integers, floats, text, or mixed data [represented as objects])

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    str
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    str
 24  classfication      801 non-null    str
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    str
 30  name               801 non-null    str
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    str
 37  type2              417 non-null    str
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), str(7)
memory usage: 256.7 KB

## Describe Data `.describe()`

This generate specific statistics about your dataset by column

- Count: Counts the number of non-null observations
- Mean: Mean of the values
- std: Standard deviation of the observations
- Min: Minimum values in the object
- Max: Maximum Values in the objet
- 25% (1st Quartile / Q1): The value where 25% of the data falls below it
- 50% (Median / Q2): The middle value of the dataset (half the data is below, half is above)
- 75% (3rd Quartile / Q3): The value where 75% of the data falls below it

You can specify specific colums using dot notation. For instance to display 1 column: ie. df.against_bug.describe(), two or more columns: df[["against_bug", "against_dragon"]].describe()

In [45]:
df.describe()

,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,...,height_m,hp,percentage_male,pokedex_number,sp_attack,sp_defense,speed,weight_kg,generation,is_legendary
count,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,...,781.000000,801.000000,703.000000,801.000000,801.000000,801.000000,801.000000,781.000000,801.000000,801.000000
mean,0.996255,1.057116,0.968789,1.073970,1.068976,1.065543,1.135456,1.192884,0.985019,1.034020,...,1.163892,68.958801,55.155761,401.000000,71.305868,70.911361,66.334582,61.378105,3.690387,0.087391
std,0.597248,0.438142,0.353058,0.654962,0.522167,0.717251,0.691853,0.604488,0.558256,0.788896,...,1.080326,26.576015,20.261623,231.373075,32.353826,27.942501,28.907662,109.354766,1.930420,0.282583
min,0.250000,0.250000,0.000000,0.000000,0.250000,0.000000,0.250000,0.250000,0.000000,0.250000,...,0.100000,1.000000,0.000000,1.000000,10.000000,20.000000,5.000000,0.100000,1.000000,0.000000
25%,0.500000,1.000000,1.000000,0.500000,1.000000,0.500000,0.500000,1.000000,1.000000,0.500000,...,0.600000,50.000000,50.000000,201.000000,45.000000,50.000000,45.000000,9.000000,2.000000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,65.000000,50.000000,401.000000,65.000000,66.000000,65.000000,27.300000,4.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,...,1.500000,80.000000,50.000000,601.000000,91.000000,90.000000,85.000000,64.800000,5.000000,0.000000
max,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,14.500000,255.000000,100.000000,801.000000,194.000000,230.000000,180.000000,999.900000,7.000000,1.000000

In [57]:
df[["against_bug", "against_dragon"]].describe()

       against_bug  against_dragon
count   801.000000      801.000000
mean      0.996255        0.968789
std       0.597248        0.353058
min       0.250000        0.000000
25%       0.500000        1.000000
50%       1.000000        1.000000
75%       1.000000        1.000000
max       4.000000        2.000000

## Checking for Missing Data `.isnull().sum()`

This shows how many missing (empty) values are in each column of your dataset.

Missing data is very common in real-world datasets, so it is important to identify it before analyzing your data.

In [87]:
df.isnull().sum()

abilities              0
against_bug            0
against_dark           0
against_dragon         0
against_electric       0
against_fairy          0
against_fight          0
against_fire           0
against_flying         0
against_ghost          0
against_grass          0
against_ground         0
against_ice            0
against_normal         0
against_poison         0
against_psychic        0
against_rock           0
against_steel          0
against_water          0
attack                 0
base_egg_steps         0
base_happiness         0
base_total             0
capture_rate           0
classfication          0
defense                0
experience_growth      0
height_m              20
hp                     0
japanese_name          0
name                   0
percentage_male       98
pokedex_number         0
sp_attack              0
sp_defense             0
speed                  0
type1                  0
type2                384
weight_kg             20
generation             0
is_legendary           0
dtype: int64

## Accessing and Selecting Data

Before cleaning or analyzing your data, you need to know how to access specific parts of your dataset.

This section covers:
- Selecting columns
- Selecting rows
- Filtering data using conditions

### Selecting Columns

You can select one or more columns from your dataset.

In [18]:
# Select a single column
df["attack"]

0       49
1       62
2      100
3       52
4       64
      ...
796    101
797    181
798    101
799    107
800     95
Name: attack, Length: 801, dtype: int64

In [14]:
# Select multiple columns
df[["attack", "defense"]]

     attack  defense
0        49       49
1        62       63
2       100      123
3        52       43
4        64       58
..      ...      ...
796     101      103
797     181      131
798     101       53
799     107      101
800      95      115

[801 rows x 2 columns]

### Selecting Rows

You can select rows using their position (index).

In [16]:
# First row
df.iloc[0]

abilities            ['Overgrow', 'Chlorophyll']
against_bug                                  1.0
against_dark                                 1.0
against_dragon                               1.0
against_electric                             0.5
against_fairy                                0.5
against_fight                                0.5
against_fire                                 2.0
against_flying                               2.0
against_ghost                                1.0
against_grass                               0.25
against_ground                               1.0
against_ice                                  2.0
against_normal                               1.0
against_poison                               1.0
against_psychic                              2.0
against_rock                                 1.0
against_steel                                1.0
against_water                                0.5
attack                                        49
base_egg_steps                              5120
base_happiness                                70
base_total                                   318
capture_rate                                  45
classfication                       Seed Pokémon
defense                                       49
experience_growth                        1059860
height_m                                     0.7
hp                                            45
japanese_name                   Fushigidaneフシギダネ
name                                   Bulbasaur
percentage_male                             88.1
pokedex_number                                 1
sp_attack                                     65
sp_defense                                    65
speed                                         45
type1                                      grass
type2                                     poison
weight_kg                                    6.9
generation                                     1
is_legendary                                   0
Name: 0, dtype: object

In [17]:
# First 5 rows
df.iloc[0:5]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

### Selecting Rows and Columns Together

In [26]:
# First row, first column
df.iloc[0, 0]

"['Overgrow', 'Chlorophyll']"

In [24]:
# Rows 3-4, specific columns
df.iloc[3:5][["name", "attack", "defense"]]

         name  attack  defense
3  Charmander      52       43
4  Charmeleon      64       58

### Filtering Data (Conditions)

You can filter your dataset based on certain conditions, this is one of the most important tools in data analysis.

In [56]:
# Filter rows where attack is greater than 100
df[df["attack"] > 100]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
5,"['Blaze', 'Solar Power']",0.25,1.0,1.0,2.0,0.5,0.50,0.5,1.0,1.0,...,88.1,6,159,115,100,fire,flying,90.5,1,0
8,"['Torrent', 'Rain Dish']",1.00,1.0,1.0,2.0,1.0,1.00,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
14,"['Swarm', 'Sniper']",0.50,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,15,15,80,145,bug,poison,29.5,1,0
33,"['Poison Point', 'Rivalry', 'Sheer Force']",0.50,1.0,1.0,0.0,0.5,0.50,1.0,1.0,1.0,...,100.0,34,85,75,85,poison,ground,62.0,1,0
56,"['Vital Spirit', 'Anger Point', 'Defiant']",0.50,0.5,1.0,1.0,2.0,1.00,1.0,2.0,1.0,...,50.0,57,60,70,95,fighting,NaN,32.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,['Beast Boost'],0.50,0.5,1.0,1.0,2.0,0.50,2.0,4.0,1.0,...,NaN,795,137,37,151,bug,fighting,25.0,7,1
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.00,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.00,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.00,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.50,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1

In [58]:
# Multiple conditions
df[(df["attack"] > 100) & (df["defense"] > 80) & (df["type1"] == "water")]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.50,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
97,"['Hyper Cutter', 'Shell Armor', 'Sheer Force']",1.0,1.0,1.0,2.0,1.0,1.0,0.50,1.0,1.0,...,50.0,98,25,25,50,water,NaN,6.5,1,0
98,"['Hyper Cutter', 'Shell Armor', 'Sheer Force']",1.0,1.0,1.0,2.0,1.0,1.0,0.50,1.0,1.0,...,50.0,99,50,50,75,water,NaN,60.0,1,0
129,"['Intimidate', 'Moxie']",0.5,1.0,1.0,4.0,1.0,0.5,0.50,1.0,1.0,...,50.0,130,70,130,81,water,flying,235.0,1,0
159,"['Torrent', 'Sheer Force']",1.0,1.0,1.0,2.0,1.0,1.0,0.50,1.0,1.0,...,88.1,160,79,83,78,water,NaN,88.8,2,0
259,"['Torrent', 'Damp']",1.0,1.0,1.0,0.0,1.0,1.0,0.50,1.0,1.0,...,88.1,260,95,110,70,water,ground,81.9,3,0
341,"['Hyper Cutter', 'Shell Armor', 'Adaptability']",2.0,0.5,1.0,2.0,2.0,2.0,0.50,1.0,0.5,...,50.0,342,90,55,55,water,dark,32.8,3,0
366,"['Swift Swim', 'Water Veil']",1.0,1.0,1.0,2.0,1.0,1.0,0.50,1.0,1.0,...,50.0,367,94,75,52,water,NaN,27.0,3,0
381,['Drizzle'],1.0,1.0,1.0,2.0,1.0,1.0,0.50,1.0,1.0,...,NaN,382,180,160,90,water,NaN,352.0,3,1
483,"['Pressure', 'Telepathy']",1.0,1.0,2.0,1.0,2.0,1.0,0.25,1.0,1.0,...,NaN,484,150,120,100,water,dragon,336.0,4,1
564,"['Solid Rock', 'Sturdy', 'Swift Swim']",1.0,1.0,1.0,2.0,1.0,2.0,0.25,0.5,1.0,...,88.1,565,83,65,32,water,rock,81.0,5,0
745,['Schooling'],1.0,1.0,1.0,2.0,1.0,1.0,0.50,1.0,1.0,...,50.0,746,140,135,30,water,NaN,0.3,7,0

### Filtering Missing Data

You can use filtering to locate missing values in your dataset.

In [71]:
# Rows where type2 is missing
df[df["type2"].isnull()]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
6,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,7,50,64,43,water,NaN,9.0,1,0
7,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,8,65,80,58,water,NaN,22.5,1,0
8,"['Torrent', 'Rain Dish']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,88.1,9,135,115,78,water,NaN,85.5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,"['Bulletproof', 'Soundproof', 'Overcoat']",1.0,1.0,2.0,0.5,2.0,1.0,0.5,1.0,1.0,...,50.0,782,45,45,45,dragon,NaN,29.7,7,0
788,['Unaware'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,789,29,31,37,psychic,NaN,0.1,7,1
789,['Sturdy'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,790,29,131,37,psychic,NaN,999.9,7,1
795,['Beast Boost'],1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,NaN,796,173,71,83,electric,NaN,100.0,7,1
799,['Prism Armor'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1

### Sorting Data

You can sort your dataset to better understand trends.

In [79]:
# Sort by attack (highest first)
df.sort_values(by="attack", ascending=False)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
213,"['Swarm', 'Guts', 'Moxie']",0.5,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,50.0,214,40,105,75,bug,fighting,54.0,2,0
797,['Beast Boost'],1.0,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
383,['Air Lock'],0.5,1.0,2.0,1.0,2.0,0.5,0.5,1.0,1.0,...,NaN,384,180,100,115,dragon,flying,206.5,3,1
382,['Drought'],1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,NaN,383,150,90,90,ground,NaN,950.0,3,1
444,"['Sand Veil', 'Rough Skin']",1.0,1.0,2.0,0.0,2.0,1.0,0.5,1.0,1.0,...,50.0,445,120,95,92,dragon,ground,95.0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,"['Sturdy', 'Gluttony', 'Contrary']",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,50.0,213,10,230,5,bug,rock,20.5,2,0
241,"['Natural Cure', 'Serene Grace', 'Healer']",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,0.0,242,75,135,55,normal,NaN,46.8,2,0
128,"['Swift Swim', 'Rattled']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,50.0,129,15,20,80,water,NaN,10.0,1,0
439,"['Natural Cure', 'Serene Grace', 'Friend Guard']",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,0.0,440,15,65,30,normal,NaN,24.4,4,0
112,"['Natural Cure', 'Serene Grace', 'Healer']",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,0.0,113,35,105,50,normal,NaN,34.6,1,0

In [86]:
# Sort by attack (highest first), notice I am using 2 brackets at the end to see 2 columns of info, making it clearer the name AND attack values. Also using head() to view 
#small amounts of the data at once.
df.sort_values(by="attack", ascending=False)[["name", "attack"]].head(20)

          name  attack
213  Heracross     185
797    Kartana     181
383   Rayquaza     180
382    Groudon     180
444   Garchomp     170
353    Banette     165
474    Gallade     165
408  Rampardos     165
247  Tyranitar     164
288    Slaking     160
485  Regigigas     160
256   Blaziken     160
718    Diancie     160
719      Hoopa     160
126     Pinsir     155
129   Gyarados     155
358      Absol     150
14    Beedrill     150
680  Aegislash     150
381     Kyogre     150

## Conclusion

- What did you find?
- What patterns did you notice?
- What surprised you?
- Does your data answer your research question?