# What Predicts Scoring in the NBA?
---

I think the scoring will correlate to more time played as well as more games played. However there most likely be another metric because some players will score more when put in for the same amount of time. Are higher scorers attempting more or less 2 pointers? All must be considered.

In [1]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.4)
Requirement already satisfied: matplotlib in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: seaborn in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
sns.set()

In [5]:
# Replace with your file name
df = pd.read_csv("nba_player_stats_2026.csv")

# Headings Key
PLAYER_ID → Unique player identifier

RANK → Player’s rank in the dataset

PLAYER → Player name

TEAM_ID → Unique team identifier
TEAM → Team abbreviation

GP → Games played

MIN → Minutes played

FGM → Field goals made

FGA → Field goals attempted

FG_PCT → Field goal percentage

FG3M → 3-point field goals made

FG3A → 3-point field goals attempted

FG3_PCT → 3-point percentage

FTM → Free throws made

FTA → Free throws attempted

FT_PCT → Free throw percentage

OREB → Offensive rebounds

DREB → Defensive rebounds

REB → Total rebounds

AST → Assists

STL → Steals

BLK → Blocks

TOV → Turnovers

PF → Personal fouls

PTS → Points scored

EFF → Overall efficiency rating

AST_TOV → Assist-to-turnover ratio

STL_TOV → Steal-to-turnover ratio

# Calculate 2 point attempts: 

2PT Made = FGM - FG3M

2PT Attempted = FGA - FG3A

In [44]:
df.columns

Index(['PLAYER_ID', 'RANK', 'PLAYER', 'TEAM_ID', 'TEAM', 'GP', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'EFF',
       'AST_TOV', 'STL_TOV'],
      dtype='str')

In [11]:
df.head()

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1629029,1,Luka Dončić,1610612747,LAL,64,2289,693,1457,0.476,...,495,530,105,34,255,153,2143,2146,2.08,0.41
1,1628983,2,Shai Gilgeous-Alexander,1610612760,OKC,68,2259,731,1321,0.553,...,292,448,95,52,151,139,2117,2189,2.97,0.63
2,1627759,3,Jaylen Brown,1610612738,BOS,71,2443,736,1543,0.477,...,492,364,72,27,259,191,2038,1817,1.41,0.28
3,201142,4,Kevin Durant,1610612745,HOU,78,2840,716,1376,0.520,...,426,372,62,71,246,142,2026,1992,1.51,0.25
4,1630178,5,Tyrese Maxey,1610612755,PHI,70,2661,694,1501,0.462,...,290,461,130,55,171,151,1980,1893,2.70,0.76

In [45]:
lakers_roster = df[df["TEAM"] == "LAL"].sort_values(by="PTS", ascending=False)

In [46]:
lakers_roster.head(20)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1629029,1,Luka Dončić,1610612747,LAL,64,2289,693,1457,0.476,...,495,530,105,34,255,153,2143,2146,2.08,0.41
46,2544,47,LeBron James,1610612747,LAL,60,1989,473,919,0.515,...,364,432,72,35,179,81,1256,1451,2.41,0.40
50,1630559,51,Austin Reaves,1610612747,LAL,51,1762,373,762,0.490,...,240,280,56,20,151,110,1187,1195,1.85,0.37
103,1629028,104,Deandre Ayton,1610612747,LAL,72,1958,403,601,0.671,...,575,59,41,70,83,157,897,1311,0.71,0.49
137,1629060,138,Rui Hachimura,1610612747,LAL,68,1927,307,597,0.514,...,226,57,39,21,42,110,780,769,1.36,0.93
163,1631222,164,Jake LaRavia,1610612747,LAL,82,2061,240,523,0.459,...,326,145,104,38,87,196,674,881,1.67,1.20
171,1628379,172,Luke Kennard,1610612747,LAL,78,1681,236,443,0.533,...,182,174,55,8,60,101,652,798,2.90,0.92
198,203935,199,Marcus Smart,1610612747,LAL,62,1769,188,476,0.395,...,172,185,87,23,92,162,579,643,2.01,0.95
238,1629637,239,Jaxson Hayes,1610612747,LAL,66,1207,198,262,0.756,...,271,59,29,52,31,127,497,761,1.90,0.94
331,1629020,332,Jarred Vanderbilt,1610612747,LAL,65,1128,113,240,0.471,...,292,84,55,19,56,104,288,532,1.50,0.98
363,1642261,364,Dalton Knecht,1610612747,LAL,54,553,87,191,0.455,...,75,21,11,11,23,45,228,213,0.91,0.48
382,1641733,383,Nick Smith Jr.,1610612747,LAL,30,375,70,161,0.435,...,23,31,9,2,21,28,185,134,1.48,0.43
429,1642355,429,Bronny James,1610612747,LAL,42,375,47,115,0.409,...,23,51,19,4,25,28,122,125,2.04,0.76
447,1631166,448,Drew Timme,1610612747,LAL,27,235,38,66,0.576,...,33,23,6,0,13,20,92,109,1.77,0.46
452,1628467,453,Maxi Kleber,1610612747,LAL,43,461,33,73,0.452,...,84,27,18,11,17,60,86,157,1.59,1.06
483,1642876,484,Adou Thiero,1610612747,LAL,25,149,16,31,0.516,...,28,10,7,2,9,19,47,62,1.11,0.78
488,1641723,488,Kobe Bufkin,1610612747,LAL,16,119,15,50,0.300,...,13,10,2,3,5,9,46,33,2.00,0.40
561,1643024,562,Chris Mañon,1610612747,LAL,9,46,2,6,0.333,...,10,3,5,2,1,6,7,21,3.00,5.00